name: Build and Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build and Deploy React app to GitHub Pages
      working-directory: ./frontend
      run: |
        npm i
        npm ci
        npm run build
        git config user.name github-actions
        git config user.email github-actions@github.com
        git --work-tree build add --all
        git commit -m "Automatic Build and Deploy run by GitHub Actions"
        git push origin HEAD:gh-pages --force
